#!/usr/bin/env python3
#
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
"""hrw4u-ast: Parse HRW4U input and print the AST."""

from __future__ import annotations

import argparse
import sys
from pprint import pprint

from antlr4 import InputStream, CommonTokenStream
from antlr4.error.ErrorStrategy import BailErrorStrategy

from hrw4u.hrw4uLexer import hrw4uLexer
from hrw4u.hrw4uParser import hrw4uParser
from hrw4u.errors import ThrowingErrorListener
from hrw4u.ast_visitor import ASTVisitor


def main() -> None:
    parser = argparse.ArgumentParser(description="Parse HRW4U input and print the AST.")
    parser.add_argument("input_file", nargs="?", type=argparse.FileType("r"), default=sys.stdin,
                        help="Input file (default: stdin)")
    args = parser.parse_args()

    content = args.input_file.read()
    filename = args.input_file.name if args.input_file is not sys.stdin else "<stdin>"
    if args.input_file is not sys.stdin:
        args.input_file.close()

    listener = ThrowingErrorListener(filename=filename)
    lexer = hrw4uLexer(InputStream(content))
    lexer.removeErrorListeners()
    lexer.addErrorListener(listener)

    stream = CommonTokenStream(lexer)
    parser_obj = hrw4uParser(stream)
    parser_obj.removeErrorListeners()
    parser_obj.addErrorListener(listener)
    parser_obj.errorHandler = BailErrorStrategy()

    tree = parser_obj.program()
    ast = ASTVisitor().visitProgram(tree)
    pprint(ast, width=120)


if __name__ == "__main__":
    main()
